// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHs5iyULkK7PcswLvpPQ3oqvcmpXymXc',
    appId: '1:361775573499:web:3c4412e3c3e139d559835e',
    messagingSenderId: '361775573499',
    projectId: 'news-4e9ea',
    authDomain: 'news-4e9ea.firebaseapp.com',
    storageBucket: 'news-4e9ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMesB-uR10DDZiBjfF98GJn4ENRdPHKBs',
    appId: '1:361775573499:android:fb9f873bd5e4676d59835e',
    messagingSenderId: '361775573499',
    projectId: 'news-4e9ea',
    storageBucket: 'news-4e9ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd743dfys7IcSbNYIM3mb0KurNWDdbA5Q',
    appId: '1:361775573499:ios:f4a267d8123e1c3759835e',
    messagingSenderId: '361775573499',
    projectId: 'news-4e9ea',
    storageBucket: 'news-4e9ea.appspot.com',
    iosBundleId: 'com.example.news',
  );
}
